version: "1.0"
services:
  hrmsdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pa$$w0rd!
  hrmsweb:
    image: hrmsweb
    build:
      context: .
      dockerfile: HRMS/Dockerfile
    ports:
      - 6001:80
    environment:
      - ConnectionStrings__Server=hrmsdb
      - ConnectionStrings__DB=HRMSDB
      - ConnectionStrings__Username=sa
      - ConnectionStrings__Password=Pa$$w0rd!
    depends_on:
      - hrmsdb
    restart: on-failure